openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/htds2/Provider/1.0.0
info:
  description: Provider API of Tottus
  x-Domain: Merchandising Execution
  x-Capability: Vendor Management
  version: "1.0.0"
  title: Provider
  contact:
    email: kmmoncada@tottus.com.pe
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Provider
    description: Provider of a store
security:
  - accessCode:
      - read
      - write
paths:
  /provider/{rut}:
    get:
      tags:
        - Provider
      summary: search a provider 
      operationId: GetProvider
      description: search a provider by code RUT without dvRUT
      security: 
        - accessCode: 
          - read
      parameters:
        - in: path
          name: rut
          description: RUT of provider without digit verifier (dvRut)
          required: true
          schema:
            type: string
      responses:
        200:
          description: Provider information requested
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/htds/Tottus/1.0.0#/components/schemas/Provider'
        400:
          description: bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Provider Not Found
        500:
          description: Internal server error
        501:
          description: Not Implemented
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/htds/Tottus/1.0.0#/components/schemas/Error'
    put:
      tags:
        - Provider
      summary: Updates a provider 
      operationId: updatedProvider
      description: Updates a provider to the system
      security: 
        - accessCode: 
          - write
      parameters:
        - in: path
          name: rut
          description: RUT of provider without digit verifier (dvRut)
          required: true
          schema:
            type: string
      requestBody: 
        content:
           application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/htds/Tottus/1.0.0#/components/schemas/Provider'
        required: true
      responses:
        200:
          description: Provider successfully updated
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Product not Found
        405:
          description: Store not Found
        500:
          description: Internal server error
        501:
          description: Not Implemented
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/htds/Tottus/1.0.0#/components/schemas/Error'
  /provider:
    post:
      tags:
        - Provider
      summary: Adds a provider 
      operationId: ProviderCreated
      description: Adds a provider to the system
      security: 
        - oAuth2AuthCode: 
          - write:provider
      responses:
         '200':
          description: Successful operation
         '400':
          description: Error on legacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/htds/Tottus/1.0.0#/components/schemas/Provider'

components:
  schemas:
    error:
      required:
      - userMessage
      type: object
      properties:
        userMessage:
          type: string
          description: User error message
          example: Unexpected error
        internalMessage:
          type: string
          description: Internal system error message
          example: Internal error
        moreInfo:
          type: string
          description: Additional error information
          example: Unexpected errors
      description: Standard structure for unexpected errors         
          
  securitySchemes:
    accessCode:
      type: oauth2
      description: For more information, see https://api.slack.com/docs/oauth
      flows: 
        authorizationCode:
          authorizationUrl: https://slack.com/oauth/authorize
          tokenUrl: https://slack.com/api/oauth.access
          scopes:
            read: Read provider of Tottus
            write: Write provider of Tottus